[build]
 command = "jekyll build"
 publish = "_site/"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.1"
  
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "http://danielelolli.it/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.danielelolli.it/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://danielelolli.it/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www-danielelolli-it.netlify.app/*"
  to = "https://www.danielelolli.it/:splat"
  status = 301
  force = true
